# CHAPTER 3 신경망을 소개합니다: 순전파

## 1. 예측을 수행하는 신경망

In [1]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


## 2. 복수 입력을 받아 예측하기
* 일반 코드

In [2]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
    
weights = [0.1, 0.2, 0]

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


### NumPy 코드

In [3]:
import numpy as np

weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

0.9800000000000001


## 3. 복수 출력을 하는 예측하기

In [5]:
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    
    for i in range(len(vector)):
        output[i] = number * vector[i]
        
    return output

def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


## 4. 복수 입력을 받아 복수 출력을 하는 예측

In [10]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

        #발가락 승률 관중수
weights = [[0.1, 0.1, -0.3], #부상
           [0.1, 0.2, 0.0], #승리
           [0.0, 1.3, 0.1]] #슬퍼

input = [toes[0], wlrec[0], nfans[0]]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0  
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])        
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


## 5. 예측에 관한 예측 (은닉 노드)

In [11]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

        #발가락 승률 관중수
ih_wgt = [[0.1, 0.2, -0.1], #hid[0]
          [-0.1, 0.1, 0.9], #hid[1]
          [0.1, 0.4, 0.1]] #hid[2]

        #hid[0] hid[1] hid[2]
hp_wgt = [[0.3, 1.1, -0.3], #부상
          [0.1, 0.2, 0.0], #승리
          [0.0, 1.3, 0.1]] #슬퍼

weights = [ih_wgt, hp_wgt]
input = [toes[0], wlrec[0], nfans[0]]

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
        
    return output

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0]) #ih_wgt
    pred = vect_mat_mul(hid, weights[1]) #hp_wgt
    return pred

pred = neural_network(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


### NumPy 코드

In [13]:
import numpy as np

#발가락 개수, 승률, 관중 수
ih_wgt = np.array([
    [0.1, 0.2, -0.1], #hid[0]
    [-0.1, 0.1, 0.9], #hid[1]
    [0.1, 0.4, 0.1]]).T #hid[2]


#hid[0] hid[1] hid[2]
hp_wgt = np.array([
    [0.3, 1.1, -0.3], #부상
    [0.1, 0.2, 0.0], #승리
    [0.0, 1.3, 0.1]]).T #슬퍼


#Transpose 안 하면 결과가 [ 0.496  1.256 -0.286] 이렇게 나옴

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0]) #input과 ih_wgt 내적
    pred = hid.dot(weights[1]) #hidden과 hp_wgt 내적
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)

print(pred)

[0.2135 0.145  0.5065]


## 6. NumPy 빠르게 입문하기

In [7]:
import numpy as np
a = np.array([0, 1, 2, 3]) #벡터
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]]) #행렬
d = np.zeros((2, 4)) #2 x 4 열행렬
e = np.random.rand(2, 5) #0에서 1 사이의 난수로 채워진 2 x 5행렬
print(a)
print(b)
print(c)
print(d)
print(e)
print("--------------------------------------------------------------")
print(a * 0.1) #벡터 a 안에 있는 모든 수에 스칼라 0.1을 곱함
print(c * 0.2) #행렬 c 안에 있는 모든 수에 0.2를 곱함
print(a * b) #a와 b 사이의 요소별 곱셈 (열끼리 짝지어서)
print(a * b * 0.2) #요소별 곱셈을 한 뒤 0.2로 곱함
print(a * c) #행렬 c가 a와 열 개수가 같으므로 c의 모든 행에 대해 요소별 곱셈을 수행

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.15185284 0.5917093  0.35740574 0.58947451 0.89830349]
 [0.90078981 0.60409797 0.22091783 0.96603058 0.07572882]]
--------------------------------------------------------------
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [9]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c.shape) #c는 (1, 3)행렬

(1, 3)


## Forward propagation
* 신경망을 통해 입력 데이터를 취하고 예측을 수행하는 과정을 일컬어 순전파(Forward propagation)이라고 한다.
* 활성화(activations)가 신경망을 통해 앞으로(Forward) 전달(Propagation)되기 때문
* 활성화: 가중치를 제외한 모든 예측에 대해 고유한 숫자